Feature/gyjb 193
SoftwareMaestro-LinkLip/LinkLip-Server pull request #75
Opened 2022-09-12 14:57 UTC by top7578

### ✅ Checklist

- [x] Set Reviewers

- [x] Set Labels

---

### 📕 Task
- [x] user entity 생성
- [x] oauth2 구글 소셜로그인
- [ ]  jwt 설정
- [ ] 테스트 코드 인증된 상태로 수정

2022-09-13 13:13 UTC, youngkwon02 requested changes

2022-09-13 13:13 UTC, youngkwon02 commented on .github/workflows/develop-deploy.yml
> +        if: contains(github.ref, 'oauth')
if 조건상 github ref에 oauth가 포함될때만 CI처리가 되는데, 해당 로직을 계획하신게 맞으신가요~??

2022-09-13 13:13 UTC, youngkwon02 commented on .github/workflows/gradle.yml
> +        if: contains(github.ref, 'oauth')
위와 동일합니다.

2022-09-13 13:13 UTC, youngkwon02 commented on src/main/java/com/linklip/linklipserver/config/CustomAuthenticationEntryPoint.java
> +        body.put("success", INVALID_TOKEN.getSuccess());
메시지가 INVALID인데 success인게 적절하지 않은 것 같습니다!

2022-09-13 13:13 UTC, youngkwon02 commented on src/main/java/com/linklip/linklipserver/config/filter/JwtTokenFilter.java
> +            HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
기존 Request, Response와 달리 서블릿 관련 클래스를 선택하셨는데, 그렇게 구현하신 이유가 있으신가요~??

2022-09-13 13:13 UTC, youngkwon02 commented on src/main/java/com/linklip/linklipserver/domain/User.java
> +    // private LocalDate deletedAt;
현재 대부분의 User 엔티티의 필드가 정의된 것으로 보이는데, Agile적으로 고려가 된 내용인지 궁금합니다!
닉네임이나 프로필 사진, 탈퇴기능까지 현재 계획에 포함된 것으로 이해하면 무리는 없어 보이지만, 상대적으로 우선순위가 높지 않은 것을 고려하면 올바른 설계인지 의견이 궁금합니다!

2022-09-13 13:13 UTC, youngkwon02 commented on src/main/java/com/linklip/linklipserver/domain/UserState.java
> +}
현재 ACTIVE, DELETED와 같이 두가지 상태만 존재한다면 is_deleted 등의 Boolean 값을 통해 처리하는 것이 더 간단할 것 같습니다.

2022-09-13 13:13 UTC, youngkwon02 commented on src/main/resources/application-oauth.yml
> +  token-expired-time-ms: 7200000
해당 파일 ignore 처리 안된 것 같은데 가장 우선적으로 처리 부탁드립니다~

2022-09-14 09:39 UTC, top7578 commented on .github/workflows/develop-deploy.yml
> +        if: contains(github.ref, 'oauth')
github.ref가 먼지 설명 가능할까요?

2022-09-14 09:42 UTC, top7578 commented on src/main/java/com/linklip/linklipserver/config/CustomAuthenticationEntryPoint.java
> +        body.put("success", INVALID_TOKEN.getSuccess());
다른 errorResponse들도 'success: false' 형태로 리턴해주고 있어서 다음과 같이 반환했는데 혹시 제가 잘못 인지하고 있는 부분일까요?

2022-09-14 10:32 UTC, youngkwon02 approved these changes

2022-09-14 12:40 UTC, top7578 commented on src/main/java/com/linklip/linklipserver/domain/User.java
> +    // private LocalDate deletedAt;
좋은 의견 같습니다. 수정하도록 하겠습니다

2022-09-14 12:40 UTC, top7578 commented on src/main/java/com/linklip/linklipserver/domain/UserState.java
> +}
헤딩 부분도 현재 필요할 것 같지 않아 삭제하도록 하겠습니다

2022-09-14 12:50 UTC, top7578 commented on src/main/java/com/linklip/linklipserver/config/filter/JwtTokenFilter.java
> +            HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
상속 받은 OncePerRequestFilter가 
![image](https://user-images.githubusercontent.com/39055981/190158399-894888dd-632b-4b5a-8f67-f245105041d8.png)
해당 내용으로 구현되어 있어 선택하게됐습니다!

2022-09-18 01:30 UTC, merged